### PR TITLE
Fixed compilation issue on Linux

### PR DESCRIPTION
**Pull request by gresskar**

### CODE REVIEW

**Comment by jsoulier** [comment]
Hey thanks for the PR. Right now it'll break Windows builds since Windows doesn't have libm. Ideally what you would do instead is only link if libm exists. 

```cmake
find_library(LIBM m)
if(LIBM)
    target_link_libraries(blocks ${LIBM})
endif()
```

I'll happily merge the PR if we can keep the Windows builds working.

**Comment by gresskar** [comment]
> I'll happily merge the PR if we can keep the Windows builds working.

I'll look into it tomorrow and test it on both Linux and Windows when I'm back on my desktop 👍

**Comment by jsoulier** [comment]
Do you plan on updating? Want to make sure before pushing the changes myself

**Comment by gresskar** [comment]
There we go, tested new commit on both Windows 11 and Ubuntu Linux (20.04.1 LTS) and it works fine

**Pull request merged**
